import SwiftUI

struct TransactionEditorView: View { @EnvironmentObject private var model: LedgerViewModel; @Environment(\.dismiss) private var dismiss; @Environment(\.locale) private var locale; let existing: LedgerTransaction?; @State private var kind: TransactionKind = .expense; @State private var amount = ""; @State private var categoryID: UUID?; @State private var date = Date(); @State private var note = ""; @State private var error: String?; @FocusState private var errorFocused: Bool
    var body: some View { NavigationStack { Form { Picker(L10n.text(.type), selection: $kind) { Text(L10n.text(.expense)).tag(TransactionKind.expense); Text(L10n.text(.income)).tag(TransactionKind.income) }.pickerStyle(.segmented); TextField(L10n.text(.amount), text: $amount).keyboardType(.decimalPad).accessibilityHint(L10n.text(.amountHint)); Picker(L10n.text(.category), selection: $categoryID) { Text(L10n.text(.chooseCategory)).tag(UUID?.none); ForEach(activeCategories) { Text(L10n.categoryName($0)).tag(Optional($0.id)) } }; DatePicker(L10n.text(.date), selection: $date, in: ...Date(), displayedComponents: .date); TextField(L10n.text(.noteOptional), text: $note, axis: .vertical).lineLimit(3...6); if let error { Text(error).foregroundStyle(.red).accessibilityAddTraits(.isStaticText).focused($errorFocused) } }.navigationTitle(L10n.text(existing == nil ? .addTransaction : .editTransaction)).toolbar { ToolbarItem(placement: .cancellationAction) { Button(L10n.text(.cancel)) { dismiss() }.disabled(model.isSaving) }; ToolbarItem(placement: .confirmationAction) { Button(L10n.text(model.isSaving ? .saving : (existing == nil ? .save : .saveChanges)), action: save).disabled(model.isSaving).accessibilityIdentifier("transaction.save") } } }.onAppear(perform: loadExisting).onChange(of: kind) { _, _ in categoryID = nil } }
    private var activeCategories: [LedgerCategory] { model.ledger.categories.filter { $0.kind == kind && $0.status == .active } }
    private func loadExisting() { guard let existing else { return }; kind = existing.kind; amount = amountText(existing.amountMinor, currency: existing.currency, locale: locale); categoryID = existing.categoryID; note = existing.note; date = Calendar.current.date(from: existing.occurredOn) ?? Date() }
    private func save() { guard let minor = minorAmount(amount, currency: model.ledger.currency ?? "USD", locale: locale) else { fail(L10n.validation(.invalidAmount)); return }; let comps = Calendar.current.dateComponents([.year, .month, .day], from: date); let category = activeCategories.first { $0.id == categoryID }; do { try LedgerValidator.validate(kind: kind, amountMinor: minor, category: category, date: comps, note: note); let now = Date(); let record = LedgerTransaction(id: existing?.id ?? UUID(), kind: kind, amountMinor: minor, currency: model.ledger.currency ?? "USD", categoryID: category!.id, categoryName: category!.name, occurredOn: comps, note: note, createdAt: existing?.createdAt ?? now, updatedAt: now); if model.mutate(success: .transactionSaved, failure: .transactionSaveFailed, { staged in if let index = staged.transactions.firstIndex(where: { $0.id == record.id }) { staged.transactions[index] = record } else { staged.transactions.append(record) } }) { dismiss() } else { fail(L10n.text(.transactionSaveFailed)) } } catch let error as LedgerValidationError { fail(L10n.validation(error)) } catch { fail(L10n.text(.transactionSaveFailed)) } }
    private func fail(_ message: String) { error = message; errorFocused = true; UIAccessibility.post(notification: .announcement, argument: message) }
}

struct HistoryView: View { @EnvironmentObject private var model: LedgerViewModel; @State private var selected: LedgerTransaction?
    var body: some View { NavigationStack { List { Section { MonthNavigator() }; let records = model.ledger.transactions(in: model.selectedMonth); if records.isEmpty { ContentUnavailableView(L10n.text(.noTransactions), systemImage: "list.bullet", description: Text(L10n.text(.transactionsDescription))) } else { ForEach(records) { transaction in Button { selected = transaction } label: { TransactionRow(transaction: transaction) } } } }.navigationTitle(L10n.text(.history)).sheet(item: $selected) { TransactionDetailView(transaction: $0) } } }
}

struct TransactionDetailView: View { @EnvironmentObject private var model: LedgerViewModel; @Environment(\.dismiss) private var dismiss; @Environment(\.locale) private var locale; let transaction: LedgerTransaction; @State private var editing = false; @State private var deleting = false; @State private var deleteError: String?
    var body: some View { NavigationStack { VStack(spacing: 18) { Text(L10n.text(transaction.kind == .expense ? .expense : .income)).font(.caption.bold()); Text(L10n.categoryName(transaction.categoryName)).editorialTitle(); Text(money(transaction.amountMinor, currency: transaction.currency, signed: transaction.kind, locale: locale)).font(.largeTitle.bold()).minimumScaleFactor(0.5); Text(transaction.note.isEmpty ? L10n.text(.noNote) : transaction.note); if let deleteError { Text(deleteError).foregroundStyle(.red); Button(L10n.text(.retryDelete), role: .destructive, action: delete).accessibilityIdentifier("transaction.delete.retry") }; Spacer(); Button(L10n.text(.editTransactionAction)) { editing = true }.buttonStyle(PrimaryButton()); Button(L10n.text(model.isSaving ? .deleting : .deleteTransaction), role: .destructive) { deleting = true }.disabled(model.isSaving) }.padding().navigationTitle(L10n.text(.transaction)).alert(L10n.text(.deleteTransactionTitle), isPresented: $deleting) { Button(L10n.text(.cancel), role: .cancel) {}; Button(L10n.text(.deletePermanently), role: .destructive, action: delete) } message: { Text(L10n.format(.deleteTransactionMessage, L10n.categoryName(transaction.categoryName))) }.sheet(isPresented: $editing) { TransactionEditorView(existing: transaction) } } }
    private func delete() { if model.mutate(success: .transactionDeleted, failure: .transactionDeleteFailed, { $0.transactions.removeAll { $0.id == transaction.id } }) { dismiss() } else { deleteError = L10n.text(.transactionDeleteFailed) } }
}
