import SwiftUI
import UIKit

struct EntryEditor: View {
    @Environment(\.dismiss) private var dismiss; @ObservedObject var model: AppModel; var editing: LedgerEntry?; @State private var draft = EntryDraft(); @State private var error: String?; @State private var saving = false
    init(model: AppModel, editing: LedgerEntry? = nil) { self.model = model; self.editing = editing; if let editing { _draft = State(initialValue: EntryDraft(type: editing.type, amountText: String(format: "%.2f", Double(editing.amountMinor) / 100), categoryID: editing.categoryID, occurredOn: editing.occurredOn, note: editing.note)) } }
    var body: some View { NavigationStack { Form { Section { Picker("Type", selection: $draft.type) { Text("Expense").tag(EntryType.expense); Text("Income").tag(EntryType.income) }.pickerStyle(.segmented); TextField("Amount", text: $draft.amountText).keyboardType(.decimalPad).accessibilityHint("Enter a positive amount"); Picker("Category", selection: $draft.categoryID) { Text("Choose a category").tag(UUID?.none); ForEach(model.ledger!.categories.filter { !$0.isArchived && $0.type == draft.type }) { Text($0.name).tag(Optional($0.id)) }; }.accessibilityHint("Only active \(draft.type.rawValue) categories are available"); DatePicker("Date", selection: $draft.occurredOn, in: ...Date(), displayedComponents: .date); TextField("Note (optional)", text: $draft.note, axis: .vertical).lineLimit(3...6) } header: { Text("Transaction details") } footer: { Text("Notes can contain up to 500 characters.") }; if let error { Section { Notice(text: error, error: true) } } }.navigationTitle(editing == nil ? "Add transaction" : "Edit transaction").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() }.disabled(saving) }; ToolbarItem(placement: .confirmationAction) { Button(saving ? "Saving…" : editing == nil ? "Save" : "Save changes") { save() }.disabled(saving) } } } }
    private func save() { saving = true; error = nil; Task { do { _ = try await model.repository.save(draft: draft, editingID: editing?.id); await model.refresh(); await MainActor.run { UIAccessibility.post(notification: .announcement, argument: "Transaction saved"); dismiss() } } catch { await MainActor.run { self.error = error.localizedDescription; self.saving = false } } } }
}

struct DetailView: View { @Environment(\.dismiss) private var dismiss; @ObservedObject var model: AppModel; let entry: LedgerEntry; @State private var editing = false; @State private var confirmingDelete = false
    var body: some View { NavigationStack { let ledger = model.ledger!; VStack(alignment: .leading, spacing: 16) { Text("\(entry.type.rawValue.uppercased()) · \(entry.occurredOn.formatted(date: .abbreviated, time: .omitted))").font(.caption.bold()); Text(entry.note.isEmpty ? ledger.category(for: entry.categoryID)?.name ?? "Transaction" : entry.note).editorialTitle(); Text((entry.type == .income ? "+" : "−") + money(entry.amountMinor, ledger.currencyCode)).font(.system(size: 34, weight: .bold, design: .serif)); Text("Category: \(ledger.category(for: entry.categoryID)?.name ?? "Unknown")"); Spacer(); Button("Edit transaction") { editing = true }.buttonStyle(PrimaryButton()); Button("Delete transaction", role: .destructive) { confirmingDelete = true }.frame(maxWidth: .infinity, minHeight: 44) }.padding().navigationTitle("Transaction").sheet(isPresented: $editing) { EntryEditor(model: model, editing: entry) }.alert("Delete \(entry.note.isEmpty ? "this transaction" : entry.note)?", isPresented: $confirmingDelete) { Button("Cancel", role: .cancel) {}; Button("Delete permanently", role: .destructive) { Task { try? await model.repository.delete(id: entry.id); await model.refresh(); dismiss() } } } message: { Text("This permanently removes this entry. Export a CSV first if you want a copy.") } } }
}
