import SwiftUI

struct HistoryView: View { @EnvironmentObject private var model: LedgerModel; @State private var selected: LedgerTransaction?
    var body: some View { NavigationStack { List { if model.state.transactions.isEmpty { ContentUnavailableView("No transactions yet", systemImage: "clock", description: Text("Transactions you add will appear here.")) } else { ForEach(model.state.transactions.sorted { $0.occurredOn > $1.occurredOn }) { transaction in Button { selected = transaction } label: { TransactionRow(transaction: transaction) } } } }.navigationTitle("History").sheet(item: $selected) { TransactionDetail(transaction: $0) } } }
}
struct TransactionDetail: View { let transaction: LedgerTransaction; @Environment(\.dismiss) private var dismiss; @EnvironmentObject private var model: LedgerModel; @State private var edit = false; @State private var confirmDelete = false
    var body: some View { NavigationStack { VStack(spacing: 20) { Text(transaction.kind.rawValue.uppercased()).font(.caption).foregroundStyle(.secondary); Text(transaction.note.isEmpty ? transaction.categoryName : transaction.note).editorialTitle(); Text((transaction.kind == .income ? "+" : "−") + money(transaction.amountMinor, currency: transaction.currencyCode)).font(.largeTitle.bold()); Text("\(transaction.categoryName) · \(transaction.occurredOn.formatted(date: .long, time: .omitted))"); Spacer(); PrimaryButton(title: "Edit transaction") { edit = true }; PrimaryButton(title: "Delete transaction", destructive: true) { confirmDelete = true } }.padding().navigationTitle("Transaction").confirmationDialog("Delete this transaction permanently?", isPresented: $confirmDelete, titleVisibility: .visible) { Button("Delete transaction", role: .destructive) { _ = model.mutate { $0.transactions.removeAll { $0.id == transaction.id } }; dismiss() } } message: { Text("This cannot be undone. \(transaction.categoryName) will be removed from your ledger.") }.sheet(isPresented: $edit) { TransactionEditor() } } }
}
struct InsightsView: View { @EnvironmentObject private var model: LedgerModel
    var body: some View { NavigationStack { let summary = model.state.summary(for: Date()); List { Section("This month") { LabeledContent("Income", value: money(summary.income, currency: model.state.currencyCode)); LabeledContent("Expenses", value: money(summary.expense, currency: model.state.currencyCode)); LabeledContent("Net", value: money(summary.net, currency: model.state.currencyCode)) }; Section("Expenses by category") { let expenses = model.state.transactions.filter { $0.kind == .expense }; if expenses.isEmpty { Text("No expense categories this month.") } else { ForEach(Dictionary(grouping: expenses, by: \.categoryName).sorted(by: { $0.key < $1.key }), id: \.key) { name, records in LabeledContent(name, value: money(records.reduce(0) { $0 + $1.amountMinor }, currency: model.state.currencyCode)) } } } }.navigationTitle("Monthly insights").accessibilityLabel("Monthly insights table") } }
