import SwiftUI

struct LedgerTabView: View { var body: some View { TabView { HomeView().tabItem { Label("Home", systemImage: "house") }; HistoryView().tabItem { Label("History", systemImage: "list.bullet") }; InsightsView().tabItem { Label("Insights", systemImage: "chart.pie") }; SettingsView().tabItem { Label("Settings", systemImage: "gearshape") } }.tint(.ledgerNavy) } }

struct MonthHeader: View { @Binding var month: MonthKey
    var body: some View { HStack { Button { month = month.offset(by: -1) } label: { Image(systemName: "chevron.left") }.frame(minWidth: 44, minHeight: 44).accessibilityLabel("Previous month"); Spacer(); Text(month.title).font(.caption.weight(.bold)).accessibilityAddTraits(.isHeader); Spacer(); Button { month = month.offset(by: 1) } label: { Image(systemName: "chevron.right") }.frame(minWidth: 44, minHeight: 44).accessibilityLabel("Next month") } }
}

struct HomeView: View { @EnvironmentObject private var model: LedgerModel; @State private var add = false
    var body: some View { NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 16) { MonthHeader(month: $model.month); Text("This month, clearly.").editorialTitle(); let summary = (try? model.repository.summary(in: model.month)) ?? MonthlySummary(month: model.month, incomeMinor: 0, expenseMinor: 0); VStack(alignment: .leading) { Text("NET").font(.caption.weight(.bold)); Text(model.money(summary.netMinor)).font(.system(size: 34, weight: .bold, design: .serif)); Divider(); HStack { Text("Income"); Spacer(); Text(model.money(summary.incomeMinor)).foregroundStyle(.ledgerSage) }; HStack { Text("Expenses"); Spacer(); Text(model.money(summary.expenseMinor)).foregroundStyle(.ledgerClay) } }.padding().background(Color.white.opacity(0.85), in: RoundedRectangle(cornerRadius: 18)); let records = (try? model.repository.transactions(in: model.month)) ?? []; if records.isEmpty { ContentUnavailableView("Nothing recorded yet", systemImage: "book.closed", description: Text("Add an expense or income to begin your monthly view.")) } else { Text("Recent activity").font(.headline); TransactionRows(records: Array(records.prefix(5))) } }.padding() }.navigationTitle("Ledgerly").toolbar { Button { add = true } label: { Image(systemName: "plus") }.accessibilityLabel("Add transaction") }.sheet(isPresented: $add) { TransactionFormView() } } }
}

struct TransactionRows: View { let records: [LedgerTransaction]; @EnvironmentObject private var model: LedgerModel
    var body: some View { ForEach(records) { record in NavigationLink(value: record.id) { HStack { VStack(alignment: .leading) { Text(record.categoryName).fontWeight(.semibold); Text([record.kind.title, record.note, record.occurredOn.description].compactMap { $0 }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) }; Spacer(); Text((record.kind == .expense ? "−" : "+") + model.money(record.amountMinor)).foregroundStyle(record.kind == .income ? .ledgerSage : .primary) }.padding(.vertical, 8) }.accessibilityLabel("\(record.kind.title), \(record.categoryName), \(model.money(record.amountMinor)), \(record.occurredOn.description)") } }
}

struct HistoryView: View { @EnvironmentObject private var model: LedgerModel; @State private var add = false
    var body: some View { NavigationStack { List { Section { MonthHeader(month: $model.month) }; let records = (try? model.repository.transactions(in: model.month)) ?? []; if records.isEmpty { ContentUnavailableView("No transactions yet", systemImage: "list.bullet", description: Text("Your activity will appear here, newest first.")) } else { TransactionRows(records: records) } }.navigationTitle("History").navigationDestination(for: UUID.self) { TransactionDetailView(id: $0) }.toolbar { Button { add = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $add) { TransactionFormView() } } }
}

struct InsightsView: View { @EnvironmentObject private var model: LedgerModel
    var body: some View { NavigationStack { ScrollView { let summary = (try? model.repository.summary(in: model.month)) ?? MonthlySummary(month: model.month, incomeMinor: 0, expenseMinor: 0); VStack(alignment: .leading, spacing: 16) { MonthHeader(month: $model.month); Text("Monthly picture").editorialTitle(); Text("Income \(model.money(summary.incomeMinor)) · Expenses \(model.money(summary.expenseMinor)) · Net \(model.money(summary.netMinor))").padding().background(.white, in: RoundedRectangle(cornerRadius: 16)); Text("Category breakdown").font(.headline); let records = (try? model.repository.transactions(in: model.month)) ?? []; ForEach(Dictionary(grouping: records.filter { $0.kind == .expense }, by: \ .categoryName).sorted(by: { $0.key < $1.key }), id: \ .key) { name, values in HStack { Text(name); Spacer(); Text(model.money(values.reduce(0) { $0 + $1.amountMinor })) } }.accessibilityLabel("\(name), \(model.money(values.reduce(0) { $0 + $1.amountMinor }))") } }.padding() }.navigationTitle("Insights") } }
