import SwiftUI

struct RootView: View {
    @StateObject var model: LedgerViewModel
    var body: some View { Group { if let recovery = model.recovery { RecoveryView(text: recovery, retry: model.open) } else if model.ledger == nil { OnboardingView(model: model) } else { MainTabs(model: model) } }.tint(LedgerlyStyle.navy).background(LedgerlyStyle.paper).alert("Ledgerly", isPresented: Binding(get: { model.message != nil }, set: { if !$0 { model.message = nil } })) { Button("OK", role: .cancel) {} } message: { Text(model.message ?? "") } }
}
struct RecoveryView: View { let text: String; let retry: () -> Void; var body: some View { VStack(spacing: 18) { Spacer(); Text("Ledgerly is protecting your data").editorialTitle().multilineTextAlignment(.center); Text(text + " Your existing data was not changed.").multilineTextAlignment(.center); Button("View recovery guidance") {}.buttonStyle(.bordered); Button("Try opening again", action: retry).buttonStyle(PrimaryButton()); Spacer() }.padding().accessibilityElement(children: .contain) } }
struct OnboardingView: View {
    @ObservedObject var model: LedgerViewModel; @State private var page = 0; @State private var currency = "USD"
    var body: some View { VStack(alignment: .leading, spacing: 22) { Spacer(); Text("Ledgerly").editorialTitle(); if page == 0 { Text("A calm, private place to record the money that moves through your month."); Button("Get started") { page = 1 }.buttonStyle(PrimaryButton()) } else if page == 1 { Text("Your ledger works offline and is stored in this app’s private storage. There is no account, sync, or transaction analytics. CSV export is always your choice."); Button("Continue") { page = 2 }.buttonStyle(PrimaryButton()) } else { Text("Choose your currency").editorialTitle(); Text("This selection is confirmed now and can change only before your first transaction."); Picker("Currency", selection: $currency) { Text("US Dollar (USD)").tag("USD"); Text("Euro (EUR)").tag("EUR"); Text("New Taiwan Dollar (TWD)").tag("TWD") }.pickerStyle(.navigationLink); Button("Create my ledger") { model.setup(currency: currency) }.buttonStyle(PrimaryButton()) }; Spacer() }.padding(28).background(LedgerlyStyle.paper) }
}
struct MainTabs: View { @ObservedObject var model: LedgerViewModel; var body: some View { TabView { HomeView(model: model).tabItem { Label("Home", systemImage: "house") }; HistoryView(model: model).tabItem { Label("History", systemImage: "clock") }; InsightsView(model: model).tabItem { Label("Insights", systemImage: "chart.pie") }; SettingsView(model: model).tabItem { Label("Settings", systemImage: "gearshape") } } } }
