import SwiftUI

struct TransactionFormView: View { @EnvironmentObject private var model: LedgerModel; @Environment(\.dismiss) private var dismiss; let editingID: UUID?; @State private var draft = TransactionDraft(); @State private var amount = ""; @State private var error: String?; @State private var saving = false
    init(editingID: UUID? = nil) { self.editingID = editingID }
    var body: some View { NavigationStack { Form { Section { Picker("Type", selection: $draft.kind) { ForEach(TransactionKind.allCases) { Text($0.title).tag($0) } }.pickerStyle(.segmented).onChange(of: draft.kind) { _, _ in draft.categoryID = activeCategories.first?.id }; TextField("Amount", text: $amount).keyboardType(.decimalPad).accessibilityHint("Enter an amount greater than zero."); Picker("Category", selection: Binding(get: { draft.categoryID }, set: { draft.categoryID = $0 })) { Text("Choose a category").tag(UUID?.none); ForEach(activeCategories) { Text($0.name).tag(Optional($0.id)) } }; DatePicker("Date", selection: Binding(get: { Calendar.current.date(from: DateComponents(year: draft.occurredOn.year, month: draft.occurredOn.month, day: draft.occurredOn.day)) ?? .now }, set: { draft.occurredOn = LocalDate($0) }), in: ...Date.now, displayedComponents: .date); TextField("Note (optional)", text: $draft.note, axis: .vertical).lineLimit(3...8) } header: { Text("Transaction details") } footer: { Text("Dates can be today or earlier. Notes can be up to 500 characters.") }; if let error { Section { Text(error).foregroundStyle(.red).accessibilityLiveRegion(.assertive) } }; Section { Button(saving ? "Saving…" : editingID == nil ? "Save \(draft.kind.rawValue)" : "Save changes") { save() }.buttonStyle(PrimaryLedgerButton()).disabled(saving) } }.navigationTitle(editingID == nil ? "Add transaction" : "Edit transaction").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() }.disabled(saving) } }.onAppear(perform: load) } }
    private var activeCategories: [LedgerCategory] { (try? model.repository.categories(status: .active, kind: draft.kind)) ?? [] }
    private func load() { guard let editingID, let record = try? model.repository.open().transactions.first(where: { $0.id == editingID }) else { draft.categoryID = activeCategories.first?.id; return }; draft = TransactionDraft(kind: record.kind, amountMinor: record.amountMinor, categoryID: record.categoryID, occurredOn: record.occurredOn, note: record.note ?? ""); amount = String(format: "%.2f", Double(record.amountMinor) / 100) }
    private func save() { saving = true; error = nil; let normalized = amount.replacingOccurrences(of: ",", with: "."); draft.amountMinor = Decimal(string: normalized).map { NSDecimalNumber(decimal: $0 * 100).int64Value }; do { _ = try model.repository.save(draft, replacing: editingID); dismiss() } catch { self.error = error.localizedDescription }; saving = false }
}

struct TransactionDetailView: View { @EnvironmentObject private var model: LedgerModel; let id: UUID; @State private var edit = false; @State private var confirmDelete = false; @Environment(\.dismiss) private var dismiss
    var body: some View { let record = try? model.repository.open().transactions.first(where: { $0.id == id }); Group { if let record { VStack(alignment: .leading, spacing: 20) { Text("\(record.kind.title.uppercased()) · \(record.occurredOn.description)").font(.caption.weight(.bold)); Text(record.note?.isEmpty == false ? record.note! : record.categoryName).editorialTitle(); Text((record.kind == .expense ? "−" : "+") + model.money(record.amountMinor)).font(.system(size: 34, weight: .bold, design: .serif)); Text(record.categoryName); Spacer(); Button("Edit transaction") { edit = true }.buttonStyle(PrimaryLedgerButton()); Button("Delete transaction", role: .destructive) { confirmDelete = true }.frame(maxWidth: .infinity, minHeight: 44) }.padding().navigationTitle("Transaction").sheet(isPresented: $edit) { TransactionFormView(editingID: id) }.alert("Delete this transaction?", isPresented: $confirmDelete) { Button("Cancel", role: .cancel) {}; Button("Delete transaction", role: .destructive) { try? model.repository.deleteTransaction(id); dismiss() } } message: { Text("This permanently removes this transaction. This can’t be undone.") } } else { ContentUnavailableView("Transaction unavailable", systemImage: "exclamationmark.triangle", description: Text("The record is no longer available.")) } } }
}
