import SwiftUI

struct TransactionForm: View {
    @Environment(\.dismiss) private var dismiss; @ObservedObject var model: LedgerViewModel; var editing: LedgerTransaction? = nil
    @State private var draft = TransactionDraft(); @State private var errors: [String: String] = [:]
    var body: some View { guard let ledger = model.ledger else { return AnyView(EmptyView()) }; return AnyView(NavigationStack { Form { Picker("Type", selection: $draft.kind) { Text("Expense").tag(TransactionKind.expense); Text("Income").tag(TransactionKind.income) }.pickerStyle(.segmented); field("AMOUNT", text: $draft.amount, prompt: "0.00", error: errors["amount"]).keyboardType(.decimalPad); Picker("CATEGORY", selection: $draft.categoryID) { Text("Choose a category").tag(UUID?.none); ForEach(ledger.categories.filter { $0.kind == draft.kind && !$0.isArchived }) { Text($0.name).tag(Optional($0.id)) } }; if let e = errors["category"] { Text(e).foregroundStyle(LedgerlyStyle.danger).font(.footnote) }; DatePicker("DATE", selection: $draft.date, in: Date.distantPast...Date(), displayedComponents: .date); if let e = errors["date"] { Text(e).foregroundStyle(LedgerlyStyle.danger).font(.footnote) }; field("NOTE (OPTIONAL)", text: $draft.note, prompt: "What was this for?", error: errors["note"]) }.navigationTitle(editing == nil ? "Add transaction" : "Edit transaction").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button(editing == nil ? "Save" : "Save changes") { errors = draft.validation(in: ledger); guard errors.isEmpty else { return }; if let editing { model.update(editing.id, draft: draft) } else { model.add(draft) }; if model.message == nil { dismiss() } }.accessibilityHint("Saves this transaction") } }.onAppear { if let tx = editing { draft = TransactionDraft(kind: tx.kind, amount: String(format: "%.2f", Double(tx.amountMinor) / 100), categoryID: tx.categoryID, date: tx.date, note: tx.note) } } }) }
    @ViewBuilder private func field(_ label: String, text: Binding<String>, prompt: String, error: String?) -> some View { VStack(alignment: .leading) { Text(label).font(.caption).fontWeight(.bold); TextField(prompt, text: text); if let error { Text(error).foregroundStyle(LedgerlyStyle.danger).font(.footnote).accessibilityLabel("Error: \(error)") } } }
}
struct TransactionDetail: View { @ObservedObject var model: LedgerViewModel; let tx: LedgerTransaction; @State private var edit = false; @State private var confirming = false; var body: some View { guard let ledger = model.ledger else { return AnyView(EmptyView()) }; return AnyView(VStack(alignment: .leading, spacing: 18) { Text(tx.kind.rawValue.uppercased() + " · " + tx.date.formatted(date: .long, time: .omitted)).font(.caption).fontWeight(.bold); Text(tx.note.isEmpty ? (ledger.categories.first(where: { $0.id == tx.categoryID })?.name ?? "Transaction") : tx.note).editorialTitle(); Text(money(tx.amountMinor, currency: ledger.currencyCode)).font(.custom("Georgia", size: 34)); Button("Edit transaction") { edit = true }.buttonStyle(PrimaryButton()); Button("Delete transaction", role: .destructive) { confirming = true }.frame(maxWidth: .infinity, minHeight: 44); Spacer() }.padding().background(LedgerlyStyle.paper).navigationTitle("Transaction").sheet(isPresented: $edit) { TransactionForm(model: model, editing: tx) }.alert("Delete this transaction?", isPresented: $confirming) { Button("Cancel", role: .cancel) {}; Button("Delete permanently", role: .destructive) { model.delete(tx.id) } } message: { Text("This permanently removes \(tx.note.isEmpty ? "this transaction" : tx.note).") }) } }
struct InsightsView: View { @ObservedObject var model: LedgerViewModel; @State private var month = Date(); var body: some View { guard let ledger = model.ledger else { return AnyView(EmptyView()) }; let totals = ledger.totals(in: month); let expenseTx = ledger.transactions.filter { $0.kind == .expense && Calendar.current.isDate($0.date, equalTo: month, toGranularity: .month) }; let categories = Dictionary(grouping: expenseTx, by: \.categoryID).map { ($0.key, $0.value.reduce(0) { $0 + $1.amountMinor }) }.sorted { $0.1 > $1.1 }; return AnyView(NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 18) { MonthPicker(month: $month); Text("Monthly view").editorialTitle(); HStack { stat("Income", totals.income, ledger); stat("Expenses", totals.expense, ledger); stat("Net", totals.income - totals.expense, ledger) }; if categories.isEmpty { ContentUnavailableView("No spending to break down", systemImage: "chart.pie", description: Text("Expenses entered this month will appear here.")) } else { Text("Expense by category").font(.headline); ForEach(categories, id: \.0) { id, amount in let name = ledger.categories.first(where: { $0.id == id })?.name ?? "Archived category"; let percent = totals.expense == 0 ? 0 : amount * 100 / totals.expense; HStack { Text(name); Spacer(); Text(money(amount, currency: ledger.currencyCode)); Text("\(percent)%").foregroundStyle(.secondary) }.ledgerCard().accessibilityLabel("\(name), \(money(amount, currency: ledger.currencyCode)), \(percent) percent of expenses") } } }.padding() }.navigationTitle("Insights") }) }
    private func stat(_ name: String, _ value: Int, _ ledger: Ledger) -> some View { VStack(alignment: .leading) { Text(name).font(.caption); Text(money(value, currency: ledger.currencyCode)).font(.headline) }.frame(maxWidth: .infinity, alignment: .leading).ledgerCard() }
}
